apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: library-kiwix-org
  namespace: zim
spec:
  secretName: library-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: library.kiwix.org
  dnsNames:
  - library.kiwix.org
