apiVersion: batch/v1
kind: Job
metadata:
  name: upload-library-logs
  namespace: zim
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: matomo-uploader
              image: ghcr.io/kiwix/matomo-log-analytics:latest
              imagePullPolicy: Always
              command: ["sh"]
              args: ["/import-logs"]
              env:
                - name: ID_SITE
                  value: "13"
                - name: URL
                  value: "https://stats.kiwix.org"
                - name: LOG
                  value: "/var/log/nginx/access.log"
                - name: USE_SUFFIXED_LOG
                  value: "y"
                - name: HOST
                  value: "library.kiwix.org"
                - name: MATOMO_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: matomo-credentials
                      key: token
              volumeMounts:
              - mountPath: "/var/log/nginx"
                name: nginx-logs-volume
                subPath: archives/library-kiwix
                readOnly: true
              - mountPath: "/import-logs"
                name: gen-scripts-volume
                subPath: "import_logs.sh"
                readOnly: true
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
          volumes:
            - name: gen-scripts-volume
              configMap:
                name: gen-scripts
                defaultMode: 0755
            - name: nginx-logs-volume
              persistentVolumeClaim:
                claimName: nginx-logs-pvc
          restartPolicy: Never
          nodeSelector:
            k8s.kiwix.org/role: "storage"
