apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyncd-configs
  namespace: zim
data:
  rsyncd.conf: |
    [global]
    charset = utf-8
    max connections = 10
    # logs already sent to stdout for k8s to handle
    # log file = /var/log/rsync.log

    # alpine-based image have xfs user on uid 33 and xfa group on gid 33
    # which corresponds to www-data/www-data on debian
    numeric ids = yes
    # allow enough time for --list-only on whole thing (20m)
    timeout = 1200

    list = yes
    uid = 33
    gid = 33
    read only = true

    # anonymous module
    [download.kiwix.org]
    path = /var/www/download.kiwix.org
    comment = Kiwix download repository
    # TODO: change this to 3 once mirrors are done migrating to auth one
    max connections = 10

    dont compress = *.zim *.gz *.xz *.bz2 *.zip *.img

    # private module for official mirrors
    [master.download.kiwix.org]
    max connections = 9
    list = no
    path = /var/www/download.kiwix.org
    comment = Kiwix download repository (mirrors only)
    hosts allow = ftp.rrze.uni-erlangen.de 131.188.12.211 mirrors.dotsrc.org 130.225.254.116 2001:878:346::116 www.mirrorservice.org 212.219.56.184 ftp.nluug.nl 145.220.21.40 poincare.acc.umu.se 130.239.18.154 2001:6b0:e:2018::154 192.115.2.70 192.115.2.0/24 ftpmirror.your.org.219.237.163.in-addr.arpa 163.237.219.7

    # Our mirrors
    # [ ] ftp.fau.de (Michael Meier <rrze-ftp-admins@fau.de>): ftp.rrze.uni-erlangen.de 131.188.12.211
    # [X] mirrors.dotsrc.org (Anders Trier Olesen <staff@dotsrc.org>): mirrors.dotsrc.org 130.225.254.116 2001:878:346::116
    # [ ] www.mirrorservice.org (Tim Bishop <help@mirrorservice.org>): www.mirrorservice.org 212.219.56.184
    # [ ] ftp.nluug.nl (Mike Hulsman  <ftpmirror-beheer@nluug.nl>): ftp.nluug.nl 145.220.21.40
    # [X] saimei.ftp.acc.umu.se (Niklas Edmundsson <ftp-adm@accum.se>): poincare.acc.umu.se 130.239.18.154 2001:6b0:e:2018::154
    # [ ] mirror.isoc.org.il: 192.115.2.70 192.115.2.0/24
    # [X] ftpmirror.your.org (Ryan Steinmetz <noc@your.org>): ftpmirror.your.org.219.237.163.in-addr.arpa 163.237.219.7

    [wmf.download.kiwix.org]
    # Ariel <ariel@wikimedia.org>
    max connections = 2
    list = no
    path = /var/www/download.kiwix.org
    comment = Kiwix download repository (wikimedia foundation only)
    hosts allow = 208.80.154.0/23

    [download.openzim.org]
    max connections = 1
    path = /var/www/download.openzim.org
    comment = openZIM download repository
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: rsyncd-app
  name: rsyncd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyncd-app
  template:
    metadata:
      labels:
        app: rsyncd-app
    spec:
      containers:
      - image: docker.io/vimagick/rsyncd:latest
        imagePullPolicy: IfNotPresent
        name: rsyncd
        command: ["rsync", "--daemon", "--no-detach", "--log-file", "/dev/stdout"]
        securityContext:
          capabilities:
            add:
              - SYS_NICE
        volumeMounts:
        - mountPath: "/var/www/download.kiwix.org"
          name: download-volume
          readOnly: true
        - mountPath: "/var/www/download.openzim.org"
          name: openzim-volume
          readOnly: true
        - mountPath: "/var/www/tmp.kiwix.org"
          name: tmp-volume
          readOnly: true
        - mountPath: "/etc/rsyncd.conf"
          name: rsyncd-configs
          subPath: rsyncd.conf
          readOnly: true
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        # we don't want to request mirrors to use an alternate port
        - containerPort: 873
          hostPort: 873
      volumes:
      - name: download-volume
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: openzim-volume
        persistentVolumeClaim:
          claimName: openzim-download-pvc
      - name: tmp-volume
        persistentVolumeClaim:
          claimName: kiwix-tmp-pvc
      - name: rsyncd-configs
        configMap:
          name: rsyncd-configs
      nodeSelector:
        k8s.kiwix.org/role: "storage"
