apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: download-kiwix-org
  namespace: zim
spec:
  secretName: download-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-identrust
  commonName: download.kiwix.org
  dnsNames:
  - download.kiwix.org
