apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirrorbrain-support-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  volumeName: mirrorbrain-support-local-pv
