apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirrorbrain-db-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: mirrorbrain-db-local-pv
