apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcher-pvc
  namespace: zimfarm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
  volumeName: zimfarm-watcher-local-pv
