apiVersion: v1
kind: PersistentVolume
metadata:
  name: zimfarm-watcher-local-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/zimfarm-watcher
  claimRef:
    name: watcher-pvc
    namespace: zimfarm
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - storage
