apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: browser-extension-kiwix-org
  namespace: pwa
spec:
  secretName: browser-extension-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: browser-extension.kiwix.org
  dnsNames:
  - browser-extension.kiwix.org
