apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pwa-kiwix-org
  namespace: pwa
spec:
  secretName: pwa-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: pwa.kiwix.org
  dnsNames:
  - pwa.kiwix.org
