apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configs
  namespace: zimit
data:
  ZIM_EXPIRATION: "7"
  LOGS_EXPIRATION: "7"
  ZIMFARM_DISALLOW_CAPABILITIES: "y"
  ALEMBIC_UPGRADE_HEAD_ON_START: "y"
