apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-farm-zimit-kiwix-org
  namespace: zimit
spec:
  secretName: api-farm-zimit-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.farm.zimit.kiwix.org
  dnsNames:
  - api.farm.zimit.kiwix.org
