apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-farm-youzim-it
  namespace: zimit
spec:
  secretName: api-farm-youzim-it-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.farm.youzim.it
  dnsNames:
  - api.farm.youzim.it
