apiVersion: v1
kind: PersistentVolume
metadata:
  name: maps-local-pv
spec:
  capacity:
    # content is 300Gi+ ATM (Apr 2022)
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/maps
  claimRef:
    name: maps-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - storage
