apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maps-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  volumeName: maps-local-pv
