apiVersion: v1
kind: PersistentVolume
metadata:
  name: debug-files-local-pv
spec:
  capacity:
    storage: 256Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/debug-files
  claimRef:
    name: debug-files-pvc
    namespace: debug
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - storage
