apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debug-files-pvc
  namespace: debug
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: debug-files-local-pv
