apiVersion: v1
kind: PersistentVolume
metadata:
  name: zimfarm-api-postgres-db-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/zimfarm/postgresdb
  claimRef:
    name: zimfarm-api-postgres-db-pvc
    namespace: zimfarm
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
