apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zimfarm-api-postgres-db-pvc
  namespace: zimfarm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: zimfarm-api-postgres-db-local-pv
