apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: farm-zimit-kiwix-org
  namespace: zimit
spec:
  secretName: farm-zimit-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: farm.zimit.kiwix.org
  dnsNames:
  - farm.zimit.kiwix.org
