apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-db-pvc
  namespace: zimfarm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: monitoring-db-local-pv
