apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-openzim-org
  namespace: zimfarm
spec:
  secretName: monitoring-openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: monitoring.openzim.org
  dnsNames:
  - monitoring.openzim.org
