apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-db-local-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/netdata
  claimRef:
    name: monitoring-db-pvc
    namespace: zimfarm
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - stats
