apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zimit-api-db-pvc
  namespace: zimit
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: zimit-api-db-local-pv
