apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cardshop-hotspot-kiwix-org
  namespace: cardshop
spec:
  secretName: cardshop-hotspot-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: cardshop.hotspot.kiwix.org
  dnsNames:
  - cardshop.hotspot.kiwix.org
