apiVersion: batch/v1
kind: CronJob
metadata:
  name: ui-media-backup
  namespace: cardshop
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: borg-backup
              image: ghcr.io/kiwix/borg-backup:latest
              imagePullPolicy: Always
              volumeMounts:
              - name: data-volume
                mountPath: "/storage"
                readOnly: true
              envFrom:
                - secretRef:
                    name: ui-media-backup-credentials
              env:
                - name: BORGBASE_NAME
                  value: "cardshop-manager-media"
                - name: BITWARDEN_EMAIL
                  value: "contact+bitwarden-slave@kiwix.org"
              command: ["single-backup"]
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  memory: 256Mi
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: cardshop-ui-media-pvc
          nodeSelector:
            k8s.kiwix.org/role: "services"
          restartPolicy: Never
