apiVersion: v1
kind: PersistentVolume
metadata:
  name: cardshop-ui-media-local-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/cardshop/media
  claimRef:
    name: cardshop-ui-media-pvc
    namespace: cardshop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
