apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardshop-ui-media-pvc
  namespace: cardshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  volumeName: cardshop-ui-media-local-pv
