apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-backup
  namespace: cluster-backup
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: cluster-backuper
          containers:
            - name: borg-backup
              image: ghcr.io/kiwix/borg-backup:latest
              imagePullPolicy: Always
              env:
                - name: BW_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: bw-client-id
                - name: BW_CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: bw-client-secret
                - name: BW_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: bw-password
                - name: BITWARDEN_EMAIL
                  valueFrom:
                    configMapKeyRef:
                      name: backup-config
                      key: bitwarden-email
                - name: BORGBASE_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: backup-config
                      key: borg-name
                - name: CLI_MODE
                  value: "y"
              command: ["entrypoint"]
              args: ["kube-dump", "all", "-d", "/storage"]
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
          restartPolicy: Never
          nodeSelector:
            k8s.kiwix.org/role: "system"

