apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-kiwix-org
  namespace: zim
spec:
  secretName: dev-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: dev.kiwix.org
  dnsNames:
  - dev.kiwix.org
