apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-drive-nginx-configs
  namespace: zim
data:
  drive.conf: |
    server {
      listen 80;
      client_body_buffer_size 1M;  # was 16k
      client_max_body_size 8192m;

      root /data;

      rewrite /_admin/logo.png /.branding/logo-512x512.png;
      rewrite /api/favicon /.branding/logo-256x256.png;
      rewrite /favicon.ico /.branding/favicon.ico;

      location = /README {
        types { } default_type "text/plain; charset=utf-8";
      }

      location / {
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime off;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: dev-drive-app
  name: dev-drive-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-drive-app
  template:
    metadata:
      labels:
        app: dev-drive-app
    spec:
      containers:
      - image: ghcr.io/openzim/surfer:latest
        imagePullPolicy: Always
        name: surfer
        env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-drive-password
                key: value
                optional: false
        volumeMounts:
        - name: data-volume
          subPath: dev
          mountPath: "/data"
          readOnly: false
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      - image: docker.io/nginx:1.21
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - name: data-volume
          mountPath: "/data"
          subPath: dev
          readOnly: true
        - name: nginx-configs
          mountPath: "/etc/nginx/conf.d/default.conf"
          subPath: drive.conf
          readOnly: true
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: nginx-configs
        configMap:
          name: dev-drive-nginx-configs
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: dev-drive-service
  labels:
    app: dev-drive-app
spec:
  selector:
    app: dev-drive-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: surfer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-drive-ingress
  namespace: zim
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8196m
spec:
  tls:
    - hosts:
      - dev.kiwix.org
      secretName: dev-kiwix-org-tls
  rules:
  - host: dev.kiwix.org
    http:
      paths:
      # welcome page link to /_admin without trailing slash
      - path: /_admin
        pathType: Exact
        backend:
          service:
            name: dev-drive-service
            port:
              name: surfer
      # the admin UI
      - path: /_admin/
        pathType: Prefix
        backend:
          service:
            name: dev-drive-service
            port:
              name: surfer
      # webdav support
      - path: /_webdav/
        pathType: Prefix
        backend:
          service:
            name: dev-drive-service
            port:
              name: surfer
      # API is used by UI
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: dev-drive-service
            port:
              name: surfer
      # branding that we overwrite
      - path: /_admin/logo.png
        pathType: Exact
        backend:
          service:
            name: dev-drive-service
            port:
              name: http
      - path: /api/favicon
        pathType: Exact
        backend:
          service:
            name: dev-drive-service
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-drive-service
            port:
              name: http
