apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwix-wiki-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/wikis/kiwix
  claimRef:
    name: kiwix-wiki-pvc
    namespace: wiki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
