apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-wiki-pvc
  namespace: wiki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: kiwix-wiki-local-pv
