apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hidden-zim-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: hidden-zim-local-pv
