apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-download-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: kiwix-download-local-pv
