apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwix-download-local-pv
spec:
  capacity:
    # content is 8.6Ti+ ATM (Apr 2022). using 1TB just so it's not mistaken
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/download
  claimRef:
    name: kiwix-download-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - storage
