apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-tmp-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
  volumeName: kiwix-tmp-local-pv
