apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-library-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: local-storage
  volumeName: kiwix-library-local-pv
