apiVersion: v1
kind: PersistentVolume
metadata:
  name: openzim-download-local-pv
spec:
  capacity:
    # content is 400Gi+ ATM (Apr 2022)
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/openzim
  claimRef:
    name: openzim-download-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - storage
