apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openzim-download-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: local-storage
  volumeName: openzim-download-local-pv
