apiVersion: v1
kind: PersistentVolume
metadata:
  name: zim-receiver-local-pv
spec:
  capacity:
    # largest ZIMs are close to 100Gi
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/zim-receiver
  claimRef:
    name: zim-receiver-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - storage
