apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: library-app
  name: library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - image: ghcr.io/kiwix/library:latest
        imagePullPolicy: Always
        name: library
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/download.kiwix.org"
          name: download-volume
          readOnly: false
        - mountPath: "/var/www/library.kiwix.org"
          name: library-volume
          readOnly: false
        - name: credentials
          mountPath: "/run/secrets/wiki-password"
          subPath: password
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
      volumes:
      - name: download-volume
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: library-volume
        persistentVolumeClaim:
          claimName: kiwix-library-pvc
      - name: credentials
        secret:
          secretName: wiki-credentials
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: library-service
  labels:
    app: library-app
spec:
  selector:
    app: library-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-ingress
  namespace: zim
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #     - library.kiwix.org
  #     secretName: library-kiwix-org-tls
  rules:
  # - host: library.kiwix.org
  - host: library-legacy.test.k8s.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: library-service
            port:
              number: 80
