apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nautilus-api-db-pvc
  namespace: nautilus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: nautilus-api-db-local-pv
