apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telco
  labels:
    app: watcherbot-app
  name: watcherbot-deployment
spec:
  # deprecated service ; example use only
  replicas: 0
  selector:
    matchLabels:
      app: watcherbot-app
  template:
    metadata:
      labels:
        app: watcherbot-app
    spec:
      containers:
      - image: docker.io/kiwix/watcherbot:latest
        imagePullPolicy: Always
        name: watcherbot
        envFrom:
        - secretRef:
            name: watcherbot-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "1m"
          limits:
            memory: "128Mi"
            cpu: "1m"
      nodeSelector:
        k8s.kiwix.org/role: "services"
