apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: download-openzim-org
  namespace: zim
spec:
  secretName: download-openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: download.openzim.org
  dnsNames:
  - download.openzim.org
