apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openzim-maps-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage
  volumeName: openzim-maps-local-pv
