apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overview-k8s-kiwix-org
  namespace: cluster-mgmt
spec:
  secretName: overview-k8s-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: overview.k8s.kiwix.org
  dnsNames:
  - overview.k8s.kiwix.org
