apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nautilus
  labels:
    app: frontend-app
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - image: ghcr.io/openzim/nautilus-webui-frontend:latest
        imagePullPolicy: Always
        name: ui
        envFrom:
        - configMapRef:
            name: frontend-configs
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: nautilus
  name: frontend-service
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: nautilus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - nautilus.openzim.org
      secretName: nautilus-openzim-org-tls
  rules:
  - host: nautilus.openzim.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
