apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nautilus-openzim-org
  namespace: nautilus
spec:
  secretName: nautilus-openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: nautilus.openzim.org
  dnsNames:
  - nautilus.openzim.org
