apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drive-farm-openzim-org
  namespace: zimfarm
spec:
  secretName: drive-farm-openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: drive.farm.openzim.org
  dnsNames:
  - drive.farm.openzim.org
