apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-viewer
  namespace: cluster-mgmt
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-viewer_cluster-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewer
subjects:
  - kind: ServiceAccount
    name: cluster-viewer
    namespace: cluster-mgmt
