apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-identrust
spec:
  acme:
    email: contact+certs@kiwix.org
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "DST Root CA X3"
    privateKeySecretRef:
      name: letsencrypt-prod-identrust
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
