apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wikifundi-es-openzim-org
  namespace: wikifundi
spec:
  secretName: wikifundi-es-openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: wikifundi-es.openzim.org
  dnsNames:
  - wikifundi-es.openzim.org
