apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-configs
  namespace: zimit
data:
  # farm-api URLs
  ZIMFARM_WEBAPI: "https://api.farm.youzim.it/v1"
  INTERNAL_ZIMFARM_WEBAPI: "https://api.farm.youzim.it/v1"
  # where to download ZIM from (for links)
  ZIM_DOWNLOAD_URL: "https://s3.us-west-1.wasabisys.com/org-kiwix-zimit"
  # user to authenticate with to farm-api
  _ZIMFARM_USERNAME: "zimit"
  # url of callback farm-api should call on task completion
  CALLBACK_BASE_URL: "https://youzim.it/api/v1/requests/hook"
  # mail sending details
  MAILGUN_API_URL: "https://api.mailgun.net/v3/mg.youzim.it"
  MAILGUN_FROM: "Youzim.it <info@youzim.it>"
  # task configuration
  ZIMIT_SIZE_LIMIT: "4294967296"
  ZIMIT_TIME_LIMIT: "7200"
  ZIMIT_IMAGE: "openzim/zimit:1.3.0"
  TASK_MEMORY: "6GiB"
  TASK_DISK: "4GiB"
  TASK_CPU: "3"
  TASK_WORKER: "sisyphus"
