apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zimit
  labels:
    app: ui-app
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - image: ghcr.io/openzim/zimit-ui:latest
        imagePullPolicy: Always
        name: ui
        envFrom:
        - configMapRef:
            name: ui-configs
        - secretRef:
            name: ui-secrets
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
    namespace: zimit
    name: ui-service
    labels:
        app: ui-app
spec:
    selector:
        app: ui-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: zimit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - youzim.it
      secretName: youzim-it-tls
  rules:
  - host: youzim.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              number: 80
