apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cardshop-github-actions-hook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-actions-hook
subjects:
- kind: User
  name: cardshop-gh-bot
  namespace: cardshop
