apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drive-local-pvc
  namespace: offspot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: offspot-drive-local-pv
