apiVersion: v1
kind: ConfigMap
metadata:
  name: maint-scripts
  namespace: zim
data:
  remove-nightlies.sh: |
    #!/bin/sh
    find /var/www/download.kiwix.org/nightly/ -mindepth 1 -maxdepth 1 -type d -mtime +30 -exec rm -rf {} \;
    find /var/www/download.openzim.org/nightly/ -mindepth 1 -maxdepth 1 -type d -mtime +30 -exec rm -rf {} \;
    find /var/www/download.openzim.org/wp1/ -mindepth 1 -maxdepth 1 -type d -mtime +730 -exec rm -rf {} \;
    # find /var/www/tmp.kiwix.org/ci/ -mindepth 1 -maxdepth 1 -mtime +30 -exec rm -rf {} \;
