apiVersion: batch/v1
kind: CronJob
metadata:
  name: mb-probe-mirrors
  namespace: zim
spec:
  schedule: "0 10 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - image: ghcr.io/kiwix/mirrorbrain:latest
              imagePullPolicy: IfNotPresent
              name: mirrorbrain
              command: ["geoipupdate -v"]
              volumeMounts:
              - name: mb-volume
                subPath: geoip2
                mountPath: "/usr/share/GeoIP"
                readOnly: false
              - name: mb-secrets
                subPath: GeoIP.conf
                readOnly: true
                mountPath: "/etc/GeoIP.conf"
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
          volumes:
          - name: mb-volume
            persistentVolumeClaim:
              claimName: mirrorbrain-support-pvc
          - name: mb-secrets
            secret:
              secretName: mb-secrets
          restartPolicy: Never
          nodeSelector:
            k8s.kiwix.org/role: "storage"
