apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cms-openzim-org
  namespace: cms
spec:
  secretName: api-cms-openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.cms.openzim.org
  dnsNames:
  - api.cms.openzim.org
