apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardshop-api-db-pvc
  namespace: cardshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: cardshop-api-db-local-pv
