apiVersion: v1
kind: PersistentVolume
metadata:
  name: cardshop-api-db-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/cardshop/mongodb
  claimRef:
    name: cardshop-api-db-pvc
    namespace: cardshop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
