apiVersion: v1
kind: ConfigMap
metadata:
  name: api-db-backup-configs
  namespace: cardshop
data:
  BITWARDEN_EMAIL: "contact+bitwarden-slave@kiwix.org"
  BORGBASE_NAME: "cardshop-scheduler-mongodb"
