apiVersion: v1
kind: PersistentVolume
metadata:
  name: nautilus-api-files-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/nautilus/files
  claimRef:
    name: nautilus-api-files-pvc
    namespace: nautilus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
