apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-farm-openzim-org
  namespace: zimfarm
spec:
  secretName: api-farm-openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.farm.openzim.org
  dnsNames:
  - api.farm.openzim.org
