apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: stats
spec:
  schedule: "0 1 * * 0"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: borg-backup
              image: ghcr.io/kiwix/borg-backup:latest
              imagePullPolicy: Always
              volumeMounts:
              - name: files-volume
                mountPath: "/storage"
                readOnly: true
              envFrom:
                - secretRef:
                    name: backup-credentials
              env:
                - name: BORGBASE_NAME
                  value: "stats"
                - name: DATABASES
                  value: "mysql://root:root@matomo-db-service:3306/all"
                - name: BITWARDEN_EMAIL
                  value: "contact+bitwarden-slave@kiwix.org"
              command: ["single-backup"]
              resources:
                requests:
                  cpu: 300m
                  memory: 256Mi
                limits:
                  memory: 256Mi
          volumes:
          - name: files-volume
            persistentVolumeClaim:
              claimName: matomo-files-pvc
          restartPolicy: Never
          nodeSelector:
            k8s.kiwix.org/role: "stats"
