apiVersion: v1
kind: ConfigMap
metadata:
  name: php-configs
  namespace: stats
data:
  memory-limit.ini: |
    memory_limit = 512M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stats
  labels:
    app: matomo-app
  name: matomo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo-app
  template:
    metadata:
      labels:
        app: matomo-app
    spec:
      containers:
      - image: docker.io/matomo:3.9.1-fpm
        imagePullPolicy: IfNotPresent
        name: matomo
        env:
          # URL to internal web service for cron upload
          - name: MATOMO_URL
            value: "http://matomo-web-service"
        volumeMounts:
        - name: files-volume
          mountPath: "/var/www/html/misc/user"
          subPath: branding
          readOnly: true
        - name: files-volume
          mountPath: "/var/www/html"
          subPath: webroot
          readOnly: false
        - name: files-volume
          mountPath: "/var/www/html/config/config.ini.php"
          subPath: config.ini.php
          readOnly: false
        - name: php-configs
          mountPath: "/usr/local/etc/php/conf.d/memory-limit.ini"
          subPath: memory-limit.ini
          readOnly: true
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      volumes:
      - name: files-volume
        persistentVolumeClaim:
          claimName: matomo-files-pvc
      - name: php-configs
        configMap:
          name: php-configs
      nodeSelector:
        k8s.kiwix.org/role: "stats"
---
apiVersion: v1
kind: Service
metadata:
  namespace: stats
  name: matomo-app-service
  labels:
    app: matomo-app
spec:
  selector:
    app: matomo-app
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
