apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-files-pvc
  namespace: stats
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeName: matomo-files-local-pv
