apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stats-kiwix-org
  namespace: stats
spec:
  secretName: stats-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: stats.kiwix.org
  dnsNames:
  - stats.kiwix.org
