apiVersion: v1
kind: PersistentVolume
metadata:
  name: stats-db-local-pv
spec:
  capacity:
    storage: 85Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/matomo/mysql/files
  claimRef:
    name: stats-db-pvc
    namespace: stats
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - stats
