apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-imager-kiwix-org
  namespace: cardshop
spec:
  secretName: api-imager-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.imager.kiwix.org
  dnsNames:
  - api.imager.kiwix.org
