apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cardshop-hotspot-kiwix-org
  namespace: cardshop
spec:
  secretName: api-cardshop-hotspot-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.cardshop.hotspot.kiwix.org
  dnsNames:
  - api.cardshop.hotspot.kiwix.org
