apiVersion: batch/v1
kind: CronJob
metadata:
  name: releases-feed-gen
  namespace: zim
spec:
  # we want it after completion of release redirects and nginx reload
  schedule: "15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: alpine
              image: docker.io/library/python:3.10-alpine
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - mountPath: "/var/www/download.openzim.org"
                name: openzim-volume
                readOnly: false
              - mountPath: "/var/www/download.kiwix.org"
                name: kiwix-volume
                readOnly: false
              - mountPath: "/create_release_feeds.py"
                name: gen-scripts-volume
                subPath: "create_release_feeds.py"
                readOnly: true
              - mountPath: "/usr/local/bin/genRSS.py"
                name: gen-scripts-volume
                subPath: "genRSS.py"
                readOnly: true
              command: ["python3"]
              args: ["create_release_feeds.py"]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
          volumes:
            - name: gen-scripts-volume
              configMap:
                name: gen-scripts
                defaultMode: 0755
            - name: openzim-volume
              persistentVolumeClaim:
                claimName: openzim-download-pvc
            - name: kiwix-volume
              persistentVolumeClaim:
                claimName: kiwix-download-pvc
          restartPolicy: Never
          nodeSelector:
            k8s.kiwix.org/role: "storage"
