apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-db-pvc
  namespace: cms
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: cms-db-local-pv
