apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openzim-wiki-pvc
  namespace: wiki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: openzim-wiki-local-pv
