apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openzim-org
  namespace: wiki
spec:
  secretName: openzim-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: openzim.org
  dnsNames:
  - openzim.org
