apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-db-local-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/metrics/elasticsearch
  claimRef:
    name: metrics-db-pvc
    namespace: metrics
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - stats
