apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-db-pvc
  namespace: metrics
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: local-storage
  volumeName: metrics-db-local-pv
